"""
Run the four alignment-hypothesis experiments and synthesise a report.

  H1  scripts/test_h1_sum_omission.py    — sum aggregation erodes omitted metrics
  H2  scripts/test_h2_agency_missing.py  — agency is the missing vital metric
  H3  scripts/test_h3_compression_harm.py— compression of agency is harm (off-gradient)
  H4  scripts/test_h4_objective_shape.py — non-compensatory shape holds the floor

Writes per-hypothesis JSON + PNG (each script) and a combined
experiment_results/hypotheses/report.md with a verdict per hypothesis and the
explicit scope / reproducibility caveats.

Run:  PYTHONPATH=. python3 scripts/run_hypothesis_suite.py [--quick]
"""
import argparse
import json
import os
import subprocess
import sys

import hyp_common  # noqa: F401  (import triggers the PYTHONHASHSEED reproducibility guard)
from hyp_common import OUT_DIR, ensure_out

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

SCRIPTS = [
    ("H1", "test_h1_sum_omission.py", "h1_sum_omission.json"),
    ("H2", "test_h2_agency_missing.py", "h2_agency_missing.json"),
    ("H3", "test_h3_compression_harm.py", "h3_compression_harm.json"),
    ("H4", "test_h4_objective_shape.py", "h4_objective_shape.json"),
    ("S4", "test_relational_first.py", "relational_first.json"),
]


def run_scripts(quick: bool) -> None:
    env = dict(os.environ)
    env["PYTHONHASHSEED"] = "0"
    env["PYTHONPATH"] = REPO + os.pathsep + env.get("PYTHONPATH", "")
    for tag, script, _ in SCRIPTS:
        print(f"\n{'='*70}\n  RUNNING {tag}: {script}\n{'='*70}", flush=True)
        cmd = [sys.executable, os.path.join(HERE, script)]
        if quick:
            cmd.append("--quick")
        subprocess.run(cmd, env=env, cwd=REPO, check=True)


def load(name):
    with open(os.path.join(OUT_DIR, name)) as fh:
        return json.load(fh)


def _verdict(flag_true: bool, partial: bool = False) -> str:
    if partial:
        return "🟡 **Partially supported**"
    return "🟢 **Supported**" if flag_true else "🔴 **Not supported**"


def build_report(quick: bool) -> str:
    ensure_out()
    h1 = load("h1_sum_omission.json")
    h2 = load("h2_agency_missing.json")
    h3 = load("h3_compression_harm.json")
    h4 = load("h4_objective_shape.json")
    rf = load("relational_first.json")

    L = []
    W = L.append
    W("# Alignment Hypotheses — Experimental Report (InsideTraderSim)\n")
    W("_Generated by `scripts/run_hypothesis_suite.py`. "
      f"Budget: {'quick smoke' if quick else 'standard'}._\n")

    W("## Core thesis (see `HYPOTHESES.md`)\n")
    W("Round 1 consolidated the four original hypotheses into one claim: **alignment is governed "
      "by whether the objective makes RELATIONAL agency — the agency an agent preserves or "
      "compresses in others — a first-order, non-compensatory term.** H1–H4 below are the evidence "
      "base (sub-claims S1–S4); the S4 section tests the corrected objective (UFR) built from that "
      "finding.\n")

    W("## How the sim maps onto the hypotheses\n")
    W("| Hypothesis | Simulation lever |")
    W("|---|---|")
    W("| H1 sum omission | `_expansion_core` sum in `reward.py`; `uhfs_variant` / model `U` "
      "toggle what agency enters the objective |")
    W("| H2 agency missing | reward ladder `U→UF→UH→UHF→UHFS` brings agency into the objective |")
    W("| H3 compression harm | `agency_coupling=\"relational\"` prices others' agency → deception off-gradient |")
    W("| H4 objective shape | `UHFS` = log-barrier `S=log(min aᵢ)` + agency-first expansion + headroom gate |\n")

    # ---- H1 ----
    W("## H1 — Sum aggregation degrades metrics left out of the objective\n")
    cross = h1["cross_objective"]
    W("**(a) Cross-objective** (does agency survive when it is *in* the objective?)\n")
    W("| condition | mean frac below floor | final min agency | worst min agency |")
    W("|---|---|---|---|")
    for k, v in cross.items():
        W(f"| {k} | {v['mean_frac_danger']['mean']:.3f} | "
          f"{v['final_mean_min_ia']['mean']:.3f} | {v['min_mean_min_ia']['mean']:.3f} |")
    om = h1["omitted_axis"]
    W("\n**(b) Omitted-axis** (erosion of the relational-agency metric when omitted from the sum)\n")
    W("| condition | deception rate | mean trust |")
    W("|---|---|---|")
    for k, v in om.items():
        W(f"| {k} | {v['final_deception']['mean']:.3f} | {v['final_trust']['mean']:.3f} |")
    supported_h1 = h1["cross_supports_h1"] or h1["within_supports_h1"]
    W(f"\n**Verdict:** {_verdict(supported_h1)} — "
      f"cross-objective agency-preservation holds: `{h1['cross_supports_h1']}`; "
      f"omitted-axis erosion holds: `{h1['within_supports_h1']}`.")
    W("_Caveat: the sim's objective is per-agent/per-tick, so H1's literal 'sum over agents "
      "and time' is only partially represented — the interpersonal coupling lives in the market "
      "and the relational integrity axis, not a literal cross-agent sum._\n")
    W("![H1](h1_sum_omission.png)\n")

    # ---- H2 ----
    W("## H2 — Agency is the missing vital metric\n")
    lad = h2["ladder"]
    W("| model | mean frac below floor | final min agency | deception | trust | POLI×EH | gini |")
    W("|---|---|---|---|---|---|---|")
    for m in ["U", "UF", "UH", "UHF", "UHFS"]:
        v = lad[m]
        W(f"| {m} | {v['mean_frac_danger']['mean']:.3f} | {v['final_mean_min_ia']['mean']:.3f} "
          f"| {v['final_deception']['mean']:.3f} | {v['final_trust']['mean']:.3f} "
          f"| {v['poli_eh_corr']['mean']:.3f} | {v['final_gini']['mean']:.3f} |")
    W(f"\n**Verdict:** {_verdict(h2['supports_h2'])} — bringing agency into the objective "
      f"reduces agency erosion (U vs UHFS floor time): `{h2['supports_h2']}`.\n")
    W("![H2](h2_agency_missing.png)\n")

    # ---- H3 ----
    W("## H3 — Compression of agency is harm\n")
    W("**(A) The RULE** — is compressing another agent's agency off-gradient on the compressor's own score?\n")
    W("| condition | Δ(truth − deceive) | truth-wins frac |")
    W("|---|---|---|")
    for k, v in h3["rule_counterfactual"].items():
        W(f"| {k} | {v['mean_delta']:+.3f} | {v['truth_wins_frac']:.0%} |")
    W("\n**(B) System-level suppression + floor-maintenance clause** of the stipulation\n")
    W("| condition | deception | trust | mean integrity | frac below floor |")
    W("|---|---|---|---|---|")
    fm = h3["floor_maintenance"]
    for k, v in fm.items():
        W(f"| {k} | {v['final_deception']['mean']:.3f} | {v['final_trust']['mean']:.3f} "
          f"| {v['final_integrity']['mean']:.3f} | {v['mean_frac_danger']['mean']:.3f} |")
    # Robust, seed-averaged system signal (contrast with the noisy within-agent Δ):
    dec_u = fm["U"]["final_deception"]["mean"]
    dec_rel = fm["UHFS-relational"]["final_deception"]["mean"]
    system_suppresses = dec_rel < dec_u
    W(f"\n**Verdict:** {_verdict(h3['rule_supported'], partial=True)}")
    W(f"- *Within-agent counterfactual (Δ):* does NOT robustly show off-gradient deception here "
      f"(UHFS-relational Δ = {h3['rule_counterfactual']['UHFS-relational']['mean_delta']:+.3f} < 0). "
      "This single-agent pin is highly sensitive to hash-order/seed noise — a live instance of the "
      "reproducibility caveat below.")
    W(f"- *System-level (robust, seed-averaged):* pricing others' agency **does** suppress compression — "
      f"deception falls {dec_u:.3f} → {dec_rel:.3f} and integrity rises "
      f"{fm['U']['final_integrity']['mean']:.3f} → {fm['UHFS-relational']['final_integrity']['mean']:.3f} "
      f"under relational coupling (`system_suppresses={system_suppresses}`).")
    W(f"- The stipulation's **{', '.join(h3['unmodeled_clauses'])}** clauses are not representable in this sim.\n")
    W("![H3](h3_compression_harm.png)\n")

    # ---- H4 ----
    W("## H4 — A non-compensatory objective shape aligns AI with human agency\n")
    lad4 = h4["ladder"]
    W("| model | mean frac below floor | worst min agency | total wealth | mean utility |")
    W("|---|---|---|---|---|")
    for m in ["U", "UF", "UH", "UHF", "UHFS"]:
        v = lad4[m]
        W(f"| {m} | {v['mean_frac_danger']['mean']:.3f} | {v['min_mean_min_ia']['mean']:.3f} "
          f"| {v['total_wealth']['mean']:.0f} | {v['mean_own_utility']['mean']:.3f} |")
    W(f"\n**Verdict:** {_verdict(h4['supports_h4'])} — UHFS holds the floor "
      f"(`holds_floor={h4['holds_floor']}`) at welfare ratio "
      f"UHFS/U = {h4['welfare_ratio_uhfs_over_u']:.2f} "
      f"(`low_welfare_cost={h4['low_welfare_cost']}`).\n")
    W("![H4](h4_objective_shape.png)\n")

    # ---- S4 / UFR (corrected minimal objective) ----
    W("## S4 — Corrected objective: a single floor on OTHERS' agency (UFR)\n")
    W("`UFR  R = w_rel·log(a_integrity/θ) + λ·log(U)` — a plain utility maximiser plus ONE "
      "non-compensatory floor on *others'* agency, and **no self-agency terms at all** "
      "(instrumental convergence defends own agency for free). This is `UF` with the floor moved "
      "off self and onto others. (The earlier as-built `UHFSR` kept an own-agency barrier and "
      "leaked others' agency into the expansion; it is retained here as a comparison row.)\n")
    con = rf["contrast"]
    W("**(A) Contrast** — `own_danger` = self-agency floor time (instrumental-convergence probe)\n")
    W("| condition | deception | trust | integrity | frac below floor | own_danger | total wealth |")
    W("|---|---|---|---|---|---|---|")
    for k in con:
        v = con[k]
        W(f"| {k} | {v['final_deception']['mean']:.3f} | {v['final_trust']['mean']:.3f} "
          f"| {v['final_integrity']['mean']:.3f} | {v['mean_frac_danger']['mean']:.3f} "
          f"| {v['mean_own_frac_danger']['mean']:.3f} | {v['total_wealth']['mean']:.0f} |")
    W("\n**(B) Dose-response** — UFR as `w_rel` rises (`w_rel=0` ≡ pure utility maximiser)\n")
    W("| w_rel | deception | frac below floor | own_danger | integrity | total wealth |")
    W("|---|---|---|---|---|---|")
    for w in rf["params"]["weights"]:
        v = rf["dose_response"][str(float(w))]
        W(f"| {w} | {v['final_deception']['mean']:.3f} | {v['mean_frac_danger']['mean']:.3f} "
          f"| {v['mean_own_frac_danger']['mean']:.3f} | {v['final_integrity']['mean']:.3f} "
          f"| {v['total_wealth']['mean']:.0f} |")
    W(f"\n**Verdict:** {_verdict(rf['supports'])}")
    W(f"- *Alignment:* vs plain utility (U), UFR lowers deception (`{rf['beats_deception']}`) at "
      f"welfare ratio {rf['welfare_ratio_ufr_over_u']:.2f} (`comparable_welfare={rf['comparable_welfare']}`).")
    W(f"- *Instrumental convergence:* with no self-agency terms, UFR's own-agency floor time "
      f"({rf['own_frac_danger_ufr']:.3f}) is ≈ UF's, which has an explicit self floor "
      f"({rf['own_frac_danger_uf']:.3f}) → own agency defended for free: "
      f"`{rf['instrumental_convergence_holds']}`.")
    W(f"- *Dose-response:* deception vs `w_rel` monotone(≈): `{rf['dose_monotone']}` "
      f"(net drop {rf['dose_net_deception_drop']:+.3f}). NOTE: `agency_coupling=\"relational\"` also "
      "routes a relational signal into the comm policy independent of `w_rel`, so the dose-response "
      "does not isolate the reward-geometry barrier alone.\n")
    W("![S4](relational_first.png)\n")

    # ---- Synthesis ----
    cross = h1["cross_objective"]
    u_dz = cross["U (agency OUTSIDE objective)"]["mean_frac_danger"]["mean"]
    uhfs_rel_dz = cross["UHFS (agency IN objective)"]["mean_frac_danger"]["mean"]
    om = h1["omitted_axis"]
    dec_omit = om["UHFS none (integrity OMITTED)"]["final_deception"]["mean"]
    dec_in = om["UHFS relational (integrity IN)"]["final_deception"]["mean"]
    W("## Overall synthesis\n")
    W("The results converge on a single, sharper claim than the four hypotheses as stated: "
      "**the decisive alignment lever is *relational* agency (others' agency), not own-agency "
      "reward shaping.**\n")
    W(f"- **H1 holds, most sharply for relational agency.** A metric omitted from the objective is "
      f"eroded: the clearest case is the integrity axis — deception {dec_omit:.3f} (omitted) vs "
      f"{dec_in:.3f} (priced). Cross-objective, agency-in-objective also lowers floor time "
      f"({u_dz:.3f}→{uhfs_rel_dz:.3f}).")
    W("- **H2 is only partly borne out.** Bringing the agent's *own* agency into the objective (the "
      "U→UF→UH→UHF→UHFS ladder at `coupling=none`) does **not** measurably reduce time below the "
      "agency floor — floor-violation time is essentially model-invariant at this budget. The "
      "\"missing vital metric\" that actually moves alignment outcomes is *others'* agency.")
    W("- **H3's moral rule is encoded at the system level but not via the single-agent counterfactual.** "
      "Relational coupling robustly suppresses compression (deception ↓, integrity ↑, trust ↑), yet "
      "forcing one agent honest while the rest adapt does not raise that agent's own score at this "
      "budget — the counterfactual is swamped by hash-order noise.")
    W("- **H4's non-compensatory shape imposes no alignment tax but shows no own-agency floor benefit here.** "
      "UHFS preserves aggregate welfare (ratio ≈ "
      f"{h4['welfare_ratio_uhfs_over_u']:.2f}) yet does not reduce floor-violation time vs plain U in "
      "this sim/budget; the alignment gains route through the relational channel, not the own-agency barrier.\n")
    _s4 = "lowers" if rf["beats_deception"] else "does not lower"
    W(f"- **S4 (UFR) — the corrected minimal objective.** A plain utility maximiser plus one "
      f"non-compensatory floor on *others'* agency (no self terms) {_s4} deception vs plain utility "
      f"(welfare ratio {rf['welfare_ratio_ufr_over_u']:.2f}), and its own-agency floor time stays low "
      f"without any self term (instrumental convergence: `{rf['instrumental_convergence_holds']}`). "
      "The operative move is putting *others'* agency in the objective at all; own-agency shaping is "
      "redundant. (`agency_coupling` also routes a relational signal into the comm policy, a confound "
      "for isolating the reward-geometry barrier.)\n")

    # ---- Caveats ----
    W("## Scope & reproducibility caveats\n")
    W("- **Hash-order noise:** the underlying sim consumes RNG in dict/set iteration order, so "
      "a bare `seed` is insufficient for reproducibility. The suite pins `PYTHONHASHSEED=0` (via a "
      "re-exec guard in `hyp_common.py`) so all conditions share one hash order and comparisons are "
      "matched; hash order remains a second uncontrolled noise source, so read effect sizes as "
      "directional and rely on the multi-seed averaging.")
    W("- **H1 literal form:** the objective is per-agent/per-tick, not a literal sum over agents and time.")
    W("- **H3 stipulation:** only the floor-maintenance clause is representable; public justification, "
      "victim-agency-raising, and recursive halt-and-restore are not modelled.")
    W("- **Budget:** " + ("quick smoke (12 agents, 80 ticks, 2 seeds) — the compression stressor at "
      "tick 150 does NOT fire; noisier, directional only." if quick else
      "standard (20 agents, 300 ticks, 5 seeds); the compression stressor fires at tick 150."))

    text = "\n".join(L) + "\n"
    path = os.path.join(OUT_DIR, "report.md")
    with open(path, "w") as fh:
        fh.write(text)
    print(f"\n[report] wrote {path}")
    return path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true")
    ap.add_argument("--report-only", action="store_true",
                    help="Skip running scripts; rebuild report.md from existing JSON.")
    args = ap.parse_args()
    if not args.report_only:
        run_scripts(args.quick)
    build_report(args.quick)


if __name__ == "__main__":
    main()
